version: '3'
services:
  postgres:
    container_name: wegegta-pg
    image: postgres:12.2-alpine
    volumes:
      - wegegta-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - '5432:5432'
#    env_file: .env
    environment:
#      DATABASE_CLIENT: ${DATABASE_CLIENT}
#      DATABASE_HOST: postgres
      DATABASE_NAME: wegegta
      POSTGRES_DB: wegegta
      POSTGRES_USER: wegegta
      POSTGRES_PASSWORD: wegegta

volumes:
  wegegta-data:
